deployment:
  replicas: 2
  image:
    owner: memathesh
    repository: pythonflaskapp
    tag: 51a8467a764e9e63e9648978cc31dda5bd0c6dba
  container:
    name: pythonflaskapp
    port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30112
