deployment:
  replicas: 2
  image:
    owner: memathesh
    repository: pythonflaskapp
    tag: 7486f22e2640295d69dff6d198aba4e8e1d5b4ae
  container:
    name: pythonflaskapp
    port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30112
