deployment:
  replicas: 2
  image:
    owner: memathesh
    repository: pythonflaskapp
    tag: 245845253e0e41e32f79c6b5c82f300ec2ccc611
  container:
    name: pythonflaskapp
    port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30112
